version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        networks:
            app_net:
                aliases:
                    - application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=app
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        ports:
            - '12002:3306'

    mariadb:
        image: 'mariadb:10.10'
        working_dir: /application
        networks:
            app_net:
                aliases:
                    - application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=app
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        ports:
            - '12003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        networks:
            app_net:
                aliases:
                    - application
        depends_on:
            -   php-fpm
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        networks:
            app_net:
                aliases:
                    - application
        links:
            - "elasticsearch"
            - "mysql"
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'


    elasticsearch:
        image: 'docker.io/bitnami/elasticsearch:7'
        networks:
            app_net:
                aliases:
                    - application
        ports:
            - '9200:9200'


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            app_net:
                aliases:
                    - application
        links:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - '12004:80'
        restart: always
networks:
    app_net:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 127.0.0.0/24
                  gateway: 127.0.0.1